import type { MetadataRoute } from "next";

/**
 * robots.txt, generated by the App Router. Everything is open to indexing — this
 * is a single marketing site with nothing to hide — and the AI search crawlers
 * are named explicitly so the welcome is unambiguous. Listing GPTBot,
 * ClaudeBot, PerplexityBot and the rest by name (each already covered by the
 * "*" rule) is a deliberate signal that we want to be read, summarised and cited
 * by AI assistants, which is the whole point of the answer-first copy and the
 * JSON-LD. The sitemap pointer lets every crawler discover the page set.
 */

const SITE_URL = "https://mariposa.restaurant";

// AI / answer-engine crawlers we explicitly welcome (training + live retrieval).
const AI_AGENTS = [
  "GPTBot",
  "OAI-SearchBot",
  "ChatGPT-User",
  "ClaudeBot",
  "anthropic-ai",
  "Claude-Web",
  "PerplexityBot",
  "Google-Extended",
  "Applebot-Extended",
  "CCBot",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      { userAgent: "*", allow: "/" },
      ...AI_AGENTS.map((userAgent) => ({ userAgent, allow: "/" })),
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
