import type { MetadataRoute } from "next";

/**
 * sitemap.xml, generated by the App Router. Two canonical routes — the homepage
 * and the full menu — each dated so crawlers know how fresh it is. Referenced
 * from robots.txt for discovery.
 */

const SITE_URL = "https://mariposa.restaurant";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return [
    {
      url: SITE_URL,
      lastModified,
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${SITE_URL}/menu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
  ];
}
