import type { MetadataRoute } from "next";

/**
 * sitemap.xml, generated by the App Router. Mariposa is a single-page site, so
 * the map is deliberately short: the one canonical route, dated so crawlers know
 * how fresh it is. Referenced from robots.txt for discovery.
 */

const SITE_URL = "https://mariposa.restaurant";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: SITE_URL,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 1,
    },
  ];
}
