import type { MetadataRoute } from "next";
import { MENU_PUBLISHED } from "@/lib/flags";

/**
 * sitemap.xml, generated by the App Router. Two canonical routes — the homepage
 * and the full menu — each dated so crawlers know how fresh it is. Referenced
 * from robots.txt for discovery.
 */

const SITE_URL = "https://mariposa.restaurant";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  const routes: MetadataRoute.Sitemap = [
    {
      url: SITE_URL,
      lastModified,
      changeFrequency: "weekly",
      priority: 1,
    },
  ];
  // Only advertise the menu while it is published.
  if (MENU_PUBLISHED) {
    routes.push({
      url: `${SITE_URL}/menu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    });
  }
  return routes;
}
